# Generated by Django 5.2.7 on 2025-11-17 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
