# Generated by Django 5.2.7 on 2025-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventparticipant_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(default='member', max_length=32),
        ),
    ]
