# Generated by Django 5.0.6 on 2025-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=12, null=True, unique=True),
        ),
    ]
